FROM ubuntu:18.04
RUN  apt-get update \
  && apt-get install -y wget \
          openssl \
        curl \
        build-essential \
        libc6-dev \
        zlib1g-dev \
        libc6 \
        libssl-dev \
  && rm -rf /var/lib/apt/lists/*
RUN wget https://github.com/Edu4rdSHL/findomain/releases/latest/download/findomain-linux
RUN chmod +x findomain-linux
CMD ["./findomain-linux"]
