name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy --all-targets -- -D warnings
    - name: Test
      run: cargo test --verbose
